[tool.poetry]
name = "generate-swedish-sentences"
version = "1.0.0"
description = "🇸🇪 Generating Swedish sentences using a probabilistic context-free grammar"
authors = ["Max Larsson <maxslarsson@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pcfg = "^0.1"
importlib-metadata = "^3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
